spring.application.name=SmartLibrary


# MySQL Config
spring.datasource.url=jdbc:mysql://localhost:3306/smart_library
spring.datasource.username=root
spring.datasource.password=admin@123

# JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Port
server.port=8080
